name: Week 6 ML Project

on:
  push:
  pull_request:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate dataset
        run: python generate_data.py

      - name: Train and evaluate model
        run: python train.py